# Generated by Django 4.0.3 on 2022-03-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='router_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(blank=True, max_length=200, null=True)),
                ('hostname', models.CharField(blank=True, max_length=200, null=True)),
                ('loopback', models.CharField(blank=True, max_length=200, null=True)),
                ('macaddress', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'router_details',
            },
        ),
    ]
